### ISSUE TITLE
No SSR.R file error

### ISSUE THREAD

**Issue by pavlo888** [vitorheidrich/q2-srs#2]
Hi, 

I am very excited to use this new tool!!! However I got an error when trying to run the following command: 

`qiime srs SRS --i-table table3.qza --p-c-min 1000 --output-dir srs-table3`

And then I get the following error: 
`Command: SRS.R /tmp/tmpmsrygrkq/table.tsv 1000 True 1

Traceback (most recent call last):
  File "/home/sam/anaconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/q2cli/commands.py", line 329, in __call__
    results = action(**arguments)
  File "<decorator-gen-121>", line 2, in SRS
  File "/home/sam/anaconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/qiime2/sdk/action.py", line 245, in bound_callable
    output_types, provenance)
  File "/home/sam/anaconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/qiime2/sdk/action.py", line 390, in _callable_executor_
    output_views = self._callable(**view_args)
  File "/home/sam/anaconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/q2_srs/_SRS.py", line 45, in SRS
    run_commands([cmd])
  File "/home/sam/anaconda3/envs/qiime2-2020.8/lib/python3.6/site-packages/q2_srs/_SRS.py", line 28, in run_commands
    subprocess.run(cmd, check=True)
  File "/home/sam/anaconda3/envs/qiime2-2020.8/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/sam/anaconda3/envs/qiime2-2020.8/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/home/sam/anaconda3/envs/qiime2-2020.8/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'SRS.R': 'SRS.R'

Plugin error from srs:

  [Errno 2] No such file or directory: 'SRS.R': 'SRS.R'

See above for debug info.
`

Could you help me solve this issue?

**Comment by vitorheidrich** [comment]
Hi,

Thank you very much for reporting this!
 
First of all, which install option did you choose?
Well, it looks like your installation somehow lost the R script that is used to perform the actual normalization step. This file should be in the anaconda3/envs/qiime2-2020.8/bin directory (can you confirm whether SRS.R is there?). I just rechecked and both install options move the R scripts to this directory correctly.

One thing you can try is to remove the plugin and install it again using the alternative install option.

Removing the plugin:
- deactivate your qiime env
- delete the q2-srs related files from the anaconda3/envs/qiime2-2020.8 (be careful to not delete boost/geometry srs files, since they have nothing to do with q2-srs)
- reactivate your qiime env

Please let me know how I can help you any further,

Vitor

**Comment by pavlo888** [comment]
Hi @vitorheidrich,

I checked if the SSR.R file is in the qiime2-2020.8 bin and it is there. I have re-installed it with the python setup file also and it still doesn't work. 

Cheers, 
Pablo

**Comment by vitorheidrich** [comment]
Hi Pablo,

Unfortunately, I am still not able to reproduce the error, so it is hard to tell what could be happening in your case. I am confirming with the QIIME2 team whether you could be facing a qiime env related issue. I will keep you updated.

In the meantime, one thing you can try is cleaning up your current environment and nativelly reinstalling qiime2-2020.8.

`conda env remove -n qiime2-2020.8`
`conda clean --all`

Then natively install qiime2-2020.8. 

Hope this helps!

Vitor

**Comment by pavlo888** [comment]
Hi @vitorheidrich 

I have re-installed qiime2-2020.8 and installed q2-srs using python (i.e. not conda) and I still get the error. 

In the screenshot below you can see that both SRS scripts are present in the qiime2 environment. I  have checked for permissions and they are also ok. 

Any other idea of how to solve this?  

![Screenshot from 2020-12-03 23-00-28](https://user-images.githubusercontent.com/45701394/101093780-a185f780-35bb-11eb-81c5-184f92118032.png)
![Screenshot from 2020-12-03 23-04-22](https://user-images.githubusercontent.com/45701394/101093963-edd13780-35bb-11eb-90fe-637eb54cec3a.png)

**Comment by vitorheidrich** [comment]
Hi Pablo,

With the help of the QIIME2 team I was able to find a solution for this problem. Check it out this QIIME2 forum [topic](https://forum.qiime2.org/t/new-plugin-q2-srs-does-not-work-for-some-users/17684).

Now the plugin is fixed, so simply reinstall q2-srs and you should be able to use SRS within QIIME2.

Cheers,

Vitor
