### ISSUE TITLE
Easy access to the underlying data for SRScurve

### ISSUE THREAD

**Issue by mestaki** [vitorheidrich/q2-srs#4]
Hi again,

I wanted to customize the SRScurve plots, for example to change the h-lines so they would reflect max diversity at max depth for each sample (instead of currently which * I think* just is an intersection line matching max.sample.size?), but I was having trouble locating the data.
I was wondering if it would be possible to make the data calculated during SRScurve made available as a table or list or something for easier digestion? I tried looking into the resulting object but i couldn't really make much sense from it. 
Or if you can give an example of how to capture that data with the existing data structure that would be great too.
Thanks!

**Comment by vitorheidrich** [comment]
Hi,

Have you tried the Shiny app? The SRS R package features a Shiny app ('SRS.shiny.app' function) that will give you a bunch of additional information regarding the SRS normalization of your dataset.

Run the following to see if that's what you're looking for:
```
example_input_data <- as.data.frame(matrix(c(sample(1:20, 100, replace = TRUE),
                                             sample(1:30, 100, replace = TRUE),
                                             sample(1:40, 100, replace = TRUE)), nrow = 100))
colnames(example_input_data) <- c("sample_1","sample_2","sample_3")
SRS.shiny.app(example_input_data)
```
Alternatively, you can also use the SRS Shiny app with QIIME2 artifacts (feature-table) as input [here](https://vitorheidrich.shinyapps.io/srsshinyapp/).

Even if not exactly what you're looking for, maybe by examining the SRS.shiny.app implementation you will be able to come up with a function that extracts exactly the information you need. Please let me know how I can help you any further.

Thank you,

Vitor

**Comment by vitorheidrich** [comment]
@mestaki, regarding the h-line, it is actually an intersection line matching 'sample'. Because the h-lines illustrate the sampled diversity at 'sample' reads per sample, it serves as an "exploratory" Cmin to guide Cmin choice. 'Max.sample.size' is simply the x-axis limit for plotting.

**Comment by mestaki** [comment]
Hi @vitorheidrich ,
The shiny app was really cool! Didn't realize it could accept .qza, very useful!

The 3rd tab with the non-normalized diversity and %retained diversity are certainly items that I was going to manually calculate for a custom plot, that's useful that they are there.
Truth be told I'm not too familiar with shiny apps, but I'll have a look at the R codes for it [here ](https://rdrr.io/cran/SRS/src/R/SRS.shiny.app.R)to see if I can grab what I need from there, thanks again! Looks pretty straightforward. 
What I'm looking to gather is basically similar to the shiny app table, plus a few additional columns that compares different rarefying/normalizing methods, so extending on this shouldn't be too hard. 

Thanks again!
